#!/bin/bash
Person1=$1
Person2=$2

echo "$Person1: Hi $Person2, Good morning"
echo "$Person2: Good morning $Person2 "
echo "$Person1: How are you $Person2"
echo "$Person2: I am good, hoe are you $Person2"